---
- name: install ca package on rhel systems
  yum:
    name: ca-certificates
    state: present

- name: copy certificate authority to trusted ca path of the os
  copy:
    src: '{{ item }}'
    dest: '/etc/pki/ca-trust/source/anchors/'
    owner: root
    group: root
    mode: 0644
  with_items:
    - ishp_issuing_ca.crt
    - ishp_root_ca.crt
  notify: update trusted ca redhat
